### Torch base

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Tensor is created as `torch.tensor` docs: https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar = torch.tensor(3)
scalar.ndim

0

this method helps to go from `torch.tensor` to `python int`

In [3]:
scalar.item()

3

In [4]:
vector = torch.tensor([7, 6])
print(f"{vector.ndim}, {vector.shape}")

1, torch.Size([2])


In [5]:
matrix = torch.tensor([[1, 2], [3, 4]])
print(f"Matrix shape: {matrix.shape}, Matrix's first raw: {matrix[0]}")

Matrix shape: torch.Size([2, 2]), Matrix's first raw: tensor([1, 2])


In [6]:
matrix.ndim

2

In [7]:
tensor = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(f"Number of dim: {tensor.ndim}, Tensor shape: {tensor.shape}")

Number of dim: 2, Tensor shape: torch.Size([3, 3])


Random tensors `torch.rand` important cuz we init weights with random tensor and then optomoze

In [8]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3601, 0.3911, 0.1594, 0.5815],
        [0.1931, 0.7038, 0.1758, 0.1987],
        [0.3304, 0.5601, 0.5243, 0.7186]])

In [9]:
random_tensor.ndim

2

In [10]:
random_tensor.shape

torch.Size([3, 4])

In [11]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [13]:
rand_tensor2 = torch.rand(2, 2)
rand_tensor2

tensor([[0.9189, 0.5726],
        [0.4525, 0.4611]])

### Zeors and ones

In [15]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
product = ones.T@zeros

In [21]:
product, product.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([4, 4]))

In [22]:
ones.dtype

torch.float32

In [23]:
ones.size()

torch.Size([3, 4])

In [24]:
tensorf16 = torch.tensor([1,2,3], dtype=torch.float16)

In [25]:
tensorf16.dtype

torch.float16

### Tensor Manipulation

In [30]:
a = torch.tensor([1,2,3])
a + 10, torch.add(a, 10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [29]:
a * 10, torch.mul(a, 10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

component wise addition and subtraction for scalars

In [28]:
a - 10

tensor([-9, -8, -7])

In [33]:
print(tensor, "*", tensor)
print(f"equals to: {tensor * tensor}")

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) * tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
equals to: tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])


In [36]:
gg = torch.tensor([4,5,6])

In [38]:
torch.matmul(gg, gg) #is doing an inner product of them <tensor, tensor>, int this case 1x3x3x1 so we get a 1x1 object

tensor(77)

In [40]:
%time
value = 0
for i in range(len(gg)):
    value += gg[i] * gg[i]
print(value)

CPU times: user 2 μs, sys: 1 μs, total: 3 μs
Wall time: 4.77 μs
tensor(77)


In [41]:
%time
torch.matmul(gg, gg)

CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 5.01 μs


tensor(77)

In [43]:
gg@gg

tensor(77)

In [45]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device name: {device}")

Device name: cuda


In [47]:
tensor_default = torch.rand(3,3)
print(tensor_default.device)

cpu


In [50]:
tensor_default = tensor_default.to(device)
print(tensor_default.device)

cuda:0


In [53]:
torch.reshape(tensor_default, (-1,))

tensor([0.6278, 0.3389, 0.4176, 0.6534, 0.0792, 0.6149, 0.5920, 0.4359, 0.1153],
       device='cuda:0')

In [2]:
M = torch.tensor([[1.,2.,3.], [.4,5.,6.], [7.,8.,9.]])

In [3]:
torch.linalg.det(M)

tensor(-21.6000)

In [4]:
torch.linalg.cholesky(M)

_LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 3 is not positive-definite).

In [10]:
M = (M + M.T) / 2  #symetric
eps = 1e-3
M_posdef = M + eps * torch.eye(M.shape[0]) # dy def should return posdrf matrix

In [12]:
eigvals = torch.linalg.eigvalsh(M_posdef)
print(f"Eigenvalues: {eigvals}")

Eigenvalues: tensor([-2.3600,  1.5539, 15.8090])


In [30]:
def nearest_posdef(M: torch.tensor) -> torch.tensor:
    eigvals, eigvec = torch.linalg.eigh(M)
    eigvals = torch.clamp(eigvals, min = 1e-6)
    return eigvec @ torch.diag(eigvals) @ eigvec.T

In [31]:
M_nearest_pd = nearest_posdef(M)
eiganvals = torch.linalg.eigvalsh(M_nearest_pd)
print(f"eigenvalue: {eiganvals}")

eigenvalue: tensor([1.3837e-06, 1.5529e+00, 1.5808e+01])


In [33]:
L = torch.linalg.cholesky(M_nearest_pd)
print(f"Cholesky L:\n ", L)

Cholesky L:
  tensor([[1.4662e+00, 0.0000e+00, 0.0000e+00],
        [1.3023e+00, 1.9344e+00, 0.0000e+00],
        [2.7670e+00, 1.4551e+00, 2.0368e-03]])
